name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main,dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore VetClinicApp
    - name: Build
      run: dotnet build --no-restore VetClinicApp
    - name: Test
      run: dotnet test --no-build --verbosity normal VetClinicApp
